site_name: rblx-open-cloud
site_url: https://rblx-open-cloud.readthedocs.io/en/latest/
copyright: Copyright &copy; treeben77 2022-2024
repo_name: treeben77/rblx-open-cloud
repo_url: https://github.com/treeben77/rblx-open-cloud
edit_uri: tree/main/docs/
theme:
  name: material
  # logo: assets/logo.svg
  # favicon: assets/logo.svg
  features:
    - content.code.copy
    - content.action.edit
    - content.tabs.link
    - navigation.sections
    # - navigation.tabs
  palette:
    scheme: slate
extra_css:
  - extra.css
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          import:
          - https://docs.python.org/3/objects.inv
          options:
            show_source: false
            show_root_toc_entry: false
            show_root_heading: true
            members_order: source
            inherited_members: true
  - git-revision-date-localized:
      enable_creation_date: false
  - git-committers:
      enabled: true
      repository: treeben77/rblx-open-cloud
      branch: v2
extra: 
  social: 
    - icon: simple/discord
      link: https://discord.gg/4CSc9E5uQy
    - icon: simple/robloxstudio
      link: https://devforum.roblox.com/t/1991959
    - icon: simple/github
      link: https://github.com/treeben77/rblx-open-cloud

markdown_extensions:
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
use_directory_urls: false
nav:
  - Overview: index.md
  - Asynchronous: asynchronous.md
  - Guides:
    - Authentication: guides/authentication.md
    - Basic: guides/basic.md
    - Experience: guides/experience.md
    - Group: guides/group.md
    - User: guides/user.md
    - OAuth2: guides/oauth2.md
    - Migrating to v2.0: guides/v2.md
  - Reference:
    - Library: reference/library.md
    - Experience: reference/experience.md
    - Group: reference/group.md
    - User: reference/user.md
    - OAuth2: reference/oauth2.md
    - Webhook: reference/webhook.md
    - Data Store: reference/datastore.md
    - Memory Store: reference/memorystore.md
    - Exceptions: reference/exceptions.md
    - Creator: reference/creator.md