site_name: rblx-open-cloud
repo_url: https://github.com/treeben77/rblx-open-cloud
theme:
  name: material
  features:
    - content.code.copy
  palette:
    scheme: slate
plugins:
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          import:
          - url: https://docs.python-requests.org/en/master/objects.inv
            domains: [std, py]
          options:
            show_source: false
            show_root_toc_entry: false
            show_root_heading: true
            members_order: source
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
use_directory_urls: false